server:
    port: 8096

spring:
    application:
        name: ssmBlog-service
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.248.140:3306/test?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&nullNamePatternMatchesAll=true&zeroDateTimeBehavior=CONVERT_TO_NULL&tinyInt1isBit=false&autoReconnect=true&useSSL=false&pinGlobalTxToPhysicalConnection=true
        username: root
        password: 123456
        hikari:
            minimum-idle: 5
            idle-timeout: 600000
            maximum-pool-size: 10
            auto-commit: true
            pool-name: MyHikariCP
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: SELECT 1
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password: root
        jedis:
            pool:
                max-active: 8
                max-wait: -1
                max-idle: 5
                min-idle: 0
        timeout: 2000
    jackson:
        date-format: yyyy-MM-dd
        time-zone: GMT+8

mybatis:
    type-aliases-package: com.wyf.blog.ssm.domain
    mapper-locations: classpath:mapper/*.xml


#打印MybatisSql
#  file: log/server.log
logging:
    level:
        com:
            wyf:
                blog:
                    ssm:
                        mapper: debug
#  config: classpath:logback.xml